services:
  - type: web
    name: jewelcalc-backend
    env: node
    region: singapore
    plan: free
    branch: main
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    healthCheckPath: /api/health
    autoDeploy: true
    
    envVars:
      - key: NODE_ENV
        value: production
      
      - key: PORT
        value: 5000
      
      # These will be added manually in Render dashboard (Secret)
      - key: MONGODB_URI
        sync: false
      
      - key: JWT_SECRET
        sync: false
      
      - key: CORS_ORIGIN
        sync: false
      
      - key: JWT_EXPIRE
        value: 30d
      
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      
      - key: DEFAULT_TIMEZONE
        value: Asia/Kolkata
      
      - key: RATE_UPDATE_DEADLINE_HOUR
        value: 13